package dev.kxrim;

public class Main {
    public static void main(String[] args) {
        HtmlBuilder htmlBuilder = new HtmlBuilder("My First HTML Document");

        htmlBuilder.addElement("h1", "Hello, World!");
        htmlBuilder.addElement("p", "This is a sample HTML document generated by HtmlBuilder.");

        htmlBuilder.addButton("Click Me!");
        htmlBuilder.addButton("Alert Button", "alert('Button clicked!')");

        htmlBuilder.build();
    }
}
